modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="bespin"
version="1.0.0"
displayName="bespin"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="jaimi, MCreator"

[[dependencies.bespin]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



